import { auth, db, firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signOut as signOutProvisioning, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js';
import { collection, getDocs, doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js';
import { renderPermissionGrid, saveMemberRole } from './role-permissions.js';
const $=id=>document.getElementById(id);let currentUid=null,currentMember=null,members=[],provisioningAuth=null;
const POSITION_LABELS={INTERN:'Thực tập sinh',COLLABORATOR:'Cộng tác viên',STAFF:'Nhân viên',SPECIALIST:'Chuyên viên',SENIOR_SPECIALIST:'Chuyên viên cao cấp',TEAM_LEAD:'Trưởng nhóm',MANAGER:'Quản lý',DEPARTMENT_HEAD:'Trưởng phòng',DIRECTOR:'Giám đốc',OTHER:'Khác'};
const normalizePosition=p=>String(p||'STAFF').toUpperCase(),positionLabel=p=>POSITION_LABELS[normalizePosition(p)]||String(p||'Nhân viên'),normalizeRole=role=>{const r=String(role||'').toLowerCase();if(r.includes('admin'))return'ADMIN';if(r.includes('manager'))return'MANAGER';return'MEMBER'};
const roleLabel=r=>({ADMIN:'Admin',MANAGER:'Manager',MEMBER:'Member'})[r]||r,statusLabel=s=>({ACTIVE:'Active',PENDING:'Pending',SUSPENDED:'Suspended'})[s]||s,roleValue=r=>r==='ADMIN'?'org_admin':r==='MANAGER'?'manager':'org_member';
const initials=n=>String(n||'U').split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase(),safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function collectRoles(d){const r=d?.roles||{};return[...(Array.isArray(r.system)?r.system:[]),...(Array.isArray(r.organization)?r.organization:[]),...(Array.isArray(d?.role)?d.role:[d?.role].filter(Boolean))]}
function memberFrom(i,m,f){const id=i.id||f,roles=collectRoles(m),sr=String(m?.status||i?.status||'ACTIVE').toUpperCase(),status=['PENDING','SUSPENDED'].includes(sr)?sr:'ACTIVE',name=i.displayName||i.name||i.fullName||i.email||id;return{id,name,email:i.email||i.emailAddress||'',role:normalizeRole(roles.join(' ')),position:normalizePosition(m?.position||i?.position||i?.jobTitle),department:m?.department||i?.department||'',team:m?.team||i?.team||'',managerId:m?.managerId||i?.managerId||'',managerName:m?.managerName||i?.managerName||'',status,joinedAt:m?.joinedAt||m?.createdAt||i?.createdAt||null,membershipId:m?.id||null,type:'member'}}
function invitationFrom(s){const d=s.data();return{id:`invite_${s.id}`,name:d.displayName||d.name||d.email||'Lời mời thành viên',email:d.email||'',role:normalizeRole(d.role),position:normalizePosition(d.position),department:d.department||'',team:d.team||'',managerId:d.managerId||'',managerName:d.managerName||'',status:'PENDING',joinedAt:d.createdAt||null,membershipId:null,type:'invitation',inviteId:s.id}}
async function loadMembers(){const rc=$('resultCount');if(rc)rc.textContent='Đang tải...';try{const is=await getDocs(collection(db,'identities')),ms=await getDocs(collection(db,'memberships')),byUid=new Map();ms.forEach(s=>{const d=s.data(),uid=d.identityId||d.userId||d.uid||s.id.match(/^mem_(.+)_org_/)?.[1];if(uid)byUid.set(uid,{...d,id:s.id})});members=is.docs.map(s=>memberFrom({...s.data(),id:s.id},byUid.get(s.id),s.id));try{const inv=await getDocs(collection(db,'invitations'));members.push(...inv.docs.filter(s=>String(s.data()?.status||'PENDING').toUpperCase()==='PENDING').map(invitationFrom))}catch(e){console.warn('Không thể đọc invitations:',e)}if(!members.length&&currentUid){const own=await getDoc(doc(db,'identities',currentUid));if(own.exists())members=[memberFrom({...own.data(),id:currentUid},{},currentUid)]}render()}catch(e){console.error('Lỗi tải thành viên:',e);render();if(rc)rc.textContent='Không thể tải danh sách với quyền hiện tại'}}
function render(){const q=($('searchInput')?.value||'').trim().toLowerCase(),sf=$('statusFilter')?.value||'ALL',rf=$('roleFilter')?.value||'ALL',filtered=members.filter(m=>(!q||`${m.name} ${m.email} ${positionLabel(m.position)} ${m.department} ${m.team}`.toLowerCase().includes(q))&&(sf==='ALL'||m.status===sf)&&(rf==='ALL'||m.role===rf));$('totalMembers').textContent=members.length;$('activeMembers').textContent=members.filter(m=>m.status==='ACTIVE').length;$('adminMembers').textContent=members.filter(m=>m.role==='ADMIN'||m.role==='MANAGER').length;$('inactiveMembers').textContent=members.filter(m=>m.status!=='ACTIVE').length;$('resultCount').textContent=`${filtered.length} thành viên`;$('emptyState').hidden=filtered.length>0;const list=$('memberList');if(!list)return;list.innerHTML=filtered.map(m=>`<div class="member-row ${m.status!=='ACTIVE'?'is-not-active':''}" data-member-id="${safe(m.id)}" tabindex="${m.status==='ACTIVE'?'0':'-1'}" role="${m.status==='ACTIVE'?'button':'row'}" aria-disabled="${m.status!=='ACTIVE'}"><div class="member-info"><div class="member-avatar">${safe(initials(m.name))}</div><div><strong>${safe(m.name)}</strong><small>${safe(positionLabel(m.position))} · ${safe(m.email)}</small><small class="member-position">${safe(m.department||'Chưa cập nhật')}${m.team?` · ${safe(m.team)}`:''}</small></div></div><span class="role ${m.role}">${safe(roleLabel(m.role))}</span><span class="status ${m.status}">${safe(statusLabel(m.status))}</span><span class="joined">${formatDate(m.joinedAt)}</span></div>`).join('');document.querySelectorAll('.member-row').forEach(row=>{if(row.getAttribute('aria-disabled')==='true')return;const open=()=>{const m=members.find(x=>x.id===row.dataset.memberId);if(m?.status==='ACTIVE')openMemberDetail(m)};row.addEventListener('click',open);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function openMemberDetail(m){currentMember=m;const fields={detailAvatar:initials(m.name),detailName:m.name,detailEmail:m.email||'Không có email',detailPosition:positionLabel(m.position),detailRole:roleLabel(m.role),detailStatus:statusLabel(m.status),detailJoined:formatDate(m.joinedAt),detailDepartment:m.department||'Chưa cập nhật',detailTeam:m.team||'Chưa cập nhật',detailManager:m.managerName||'Chưa xác định',detailId:m.id};Object.entries(fields).forEach(([id,v])=>{const el=$(id);if(el)el.textContent=v});$('roleSelect').value=m.role;$('roleSaveStatus').textContent='';$('roleSaveStatus').className='role-save-status';renderPermissionGrid($('permissionGrid'),m.role);const o=$('memberDetailOverlay');o.hidden=false;requestAnimationFrame(()=>o.classList.add('open'))}
function closeMemberDetail(){const o=$('memberDetailOverlay');o.classList.remove('open');setTimeout(()=>o.hidden=true,120);currentMember=null}
function populateManagerSelect(){const s=$('inviteManager');s.innerHTML='<option value="">Chưa xác định</option>'+members.filter(m=>m.status==='ACTIVE').map(m=>`<option value="${safe(m.id)}">${safe(m.name)} · ${safe(positionLabel(m.position))}</option>`).join('')}
function openInvite(){const o=$('inviteOverlay');$('inviteForm').reset();populateManagerSelect();$('inviteStatus').textContent='';$('inviteStatus').className='role-save-status';$('generatedPassword').textContent='—';$('credentialsResult').hidden=true;$('sendInviteBtn').textContent='Tạo tài khoản';$('sendInviteBtn').disabled=false;o.hidden=false;requestAnimationFrame(()=>o.classList.add('open'));setTimeout(()=>$('inviteName')?.focus(),60)}
function closeInvite(){const o=$('inviteOverlay');o.classList.remove('open');setTimeout(()=>o.hidden=true,120)}
function formatDate(v){if(!v)return'—';try{const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('vi-VN')}catch{return'—'}}
function generatePassword(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=new Uint8Array(14);crypto.getRandomValues(bytes);return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('')}
async function getProvisioningAuth(){if(provisioningAuth)return provisioningAuth;provisioningAuth=getAuth(initializeApp(firebaseConfig,`saovn-provision-${Date.now()}`));return provisioningAuth}
async function provisionMemberAccount(){const name=$('inviteName').value.trim(),email=$('inviteEmail').value.trim().toLowerCase(),position=normalizePosition($('invitePosition').value),department=$('inviteDepartment').value.trim(),team=$('inviteTeam').value.trim(),managerId=$('inviteManager').value||'',manager=members.find(m=>m.id===managerId),role=$('inviteRole').value.toUpperCase(),status=$('inviteStatus'),button=$('sendInviteBtn');if(!name||!email)return;status.textContent='Đang tạo tài khoản và hồ sơ thành viên...';status.className='role-save-status pending';button.disabled=true;button.textContent='Đang tạo...';try{const iq=await getDocs(collection(db,'identities'));if(iq.docs.some(s=>String(s.data()?.email||'').toLowerCase()===email))throw new Error('Email này đã tồn tại trong SAOVN-OS.');const pa=await getProvisioningAuth(),password=generatePassword(),credential=await createUserWithEmailAndPassword(pa,email,password),uid=credential.user.uid,profile={uid,email,displayName:name,status:'ACTIVE',position,department,team,managerId,managerName:manager?.name||'',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid};await setDoc(doc(db,'identities',uid),profile);await setDoc(doc(db,'memberships',`mem_${uid}_org_saovn_01`),{uid,userId:uid,identityId:uid,organizationId:'org_saovn_01',status:'ACTIVE',position,department,team,managerId,managerName:manager?.name||'',roles:{system:[],organization:[roleValue(role)]},joinedAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid});try{await signOutProvisioning(pa)}catch(_){}$('generatedEmail').textContent=email;$('generatedPassword').textContent=password;$('credentialsResult').hidden=false;status.textContent='Đã tạo tài khoản và hồ sơ thành công.';status.className='role-save-status success';button.textContent='Tạo tài khoản khác';await loadMembers()}catch(e){console.error(e);status.textContent=e?.message||'Không thể tạo tài khoản.';status.className='role-save-status error'}finally{button.disabled=false}}
[['searchInput','input'],['statusFilter','change'],['roleFilter','change']].forEach(([id,ev])=>$(id)?.addEventListener(ev,render));$('refreshBtn').onclick=loadMembers;$('logoutBtn').onclick=()=>signOut(auth);$('detailClose').onclick=closeMemberDetail;$('memberDetailOverlay').onclick=e=>{if(e.target.id==='memberDetailOverlay')closeMemberDetail()};$('inviteMemberBtn').onclick=openInvite;$('inviteClose').onclick=closeInvite;$('inviteOverlay').onclick=e=>{if(e.target.id==='inviteOverlay')closeInvite()};$('inviteForm').onsubmit=e=>{e.preventDefault();provisionMemberAccount()};$('copyCredentials').onclick=async()=>{const email=$('generatedEmail').textContent,password=$('generatedPassword').textContent;try{await navigator.clipboard.writeText(`SAOVN-OS\nEmail: ${email}\nMật khẩu tạm: ${password}`);$('copyCredentials').textContent='Đã sao chép';setTimeout(()=>$('copyCredentials').textContent='Sao chép thông tin',1500)}catch{}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMemberDetail();closeInvite()}});$('roleSelect').onchange=e=>{renderPermissionGrid($('permissionGrid'),e.target.value);$('roleSaveStatus').textContent='Thay đổi chưa lưu';$('roleSaveStatus').className='role-save-status pending'};$('saveRoleBtn').onclick=async()=>{if(!currentMember)return;const role=$('roleSelect').value,b=$('saveRoleBtn');b.disabled=true;b.textContent='Đang lưu...';try{if(!currentMember.membershipId)throw new Error('Thành viên này chưa có Membership.');await saveMemberRole(currentMember.membershipId,role);currentMember.role=role;const target=members.find(m=>m.id===currentMember.id);if(target)target.role=role;$('detailRole').textContent=roleLabel(role);$('roleSaveStatus').textContent='Đã lưu vai trò thành công.';$('roleSaveStatus').className='role-save-status success';render()}catch(e){console.error(e);$('roleSaveStatus').textContent=e?.message||'Không thể lưu vai trò.';$('roleSaveStatus').className='role-save-status error'}finally{b.disabled=false;b.textContent='Lưu vai trò'}};onAuthStateChanged(auth,async user=>{if(!user){location.href='index.html';return}currentUid=user.uid;const display=user.displayName||user.email?.split('@')[0]||'User';$('userName').textContent=display;$('userAvatar').textContent=initials(display);await loadMembers()});