import { auth, db, firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signOut as signOutProvisioning } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js';
import { collection, getDocs, doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js';
import { renderPermissionGrid, saveMemberRole } from './role-permissions.js';

const $=id=>document.getElementById(id); let currentUid=null,currentMember=null,members=[],provisioningAuth=null;
const POSITION_LABELS={INTERN:'Thực tập sinh',COLLABORATOR:'Cộng tác viên',STAFF:'Nhân viên',SPECIALIST:'Chuyên viên',SENIOR_SPECIALIST:'Chuyên viên cao cấp',TEAM_LEAD:'Trưởng nhóm',MANAGER:'Quản lý',DEPARTMENT_HEAD:'Trưởng phòng',DIRECTOR:'Giám đốc',OTHER:'Khác'};
const normalizePosition=p=>String(p||'STAFF').toUpperCase(); const positionLabel=p=>POSITION_LABELS[normalizePosition(p)]||String(p||'Nhân viên');
const normalizeRole=role=>{const r=String(role||'').toLowerCase();if(r.includes('admin'))return'ADMIN';if(r.includes('manager'))return'MANAGER';return'MEMBER';};
const roleLabel=role=>({ADMIN:'Admin',MANAGER:'Manager',MEMBER:'Member'})[role]||role; const statusLabel=status=>({ACTIVE:'Active',PENDING:'Pending',SUSPENDED:'Suspended'})[status]||status;
const roleValue=role=>role==='ADMIN'?'org_admin':role==='MANAGER'?'manager':'org_member'; const initials=name=>String(name||'U').split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase();
const safe=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function collectRoles(data){const roles=data?.roles||{};return[...(Array.isArray(roles.system)?roles.system:[]),...(Array.isArray(roles.organization)?roles.organization:[]),...(Array.isArray(data?.role)?data.role:[data?.role].filter(Boolean))];}
function memberFrom(identity,membership,fallbackId){const id=identity.id||fallbackId,roles=collectRoles(membership),statusRaw=String(membership?.status||identity?.status||'ACTIVE').toUpperCase(),status=['PENDING','SUSPENDED'].includes(statusRaw)?statusRaw:'ACTIVE',name=identity.displayName||identity.name||identity.fullName||identity.email||id;return{id,name,email:identity.email||identity.emailAddress||'',role:normalizeRole(roles.join(' ')),position:normalizePosition(membership?.position||identity?.position||identity?.jobTitle||'STAFF'),status,joinedAt:membership?.joinedAt||membership?.createdAt||identity?.createdAt||null,membershipId:membership?.id||null,type:'member'};}
function invitationFrom(snapshot){const d=snapshot.data();return{id:`invite_${snapshot.id}`,name:d.displayName||d.name||d.email||'Lời mời thành viên',email:d.email||'',role:normalizeRole(d.role),position:normalizePosition(d.position||d.jobTitle||'STAFF'),status:'PENDING',joinedAt:d.createdAt||null,membershipId:null,type:'invitation',inviteId:snapshot.id};}
async function loadMembers(){const resultCount=$('resultCount');if(resultCount)resultCount.textContent='Đang tải...';try{const identitySnap=await getDocs(collection(db,'identities')),membershipSnap=await getDocs(collection(db,'memberships')),membershipsByUid=new Map();membershipSnap.forEach(s=>{const d=s.data(),uid=d.identityId||d.userId||d.uid||s.id.match(/^mem_(.+)_org_/)?.[1];if(uid)membershipsByUid.set(uid,{...d,id:s.id});});const activeMembers=identitySnap.docs.map(s=>memberFrom({...s.data(),id:s.id},membershipsByUid.get(s.id),s.id));let pendingInvites=[];try{const invitationSnap=await getDocs(collection(db,'invitations'));pendingInvites=invitationSnap.docs.filter(s=>String(s.data()?.status||'PENDING').toUpperCase()==='PENDING').map(invitationFrom);}catch(e){console.warn('Không thể đọc invitations:',e);}members=[...activeMembers,...pendingInvites];if(!members.length&&currentUid){const own=await getDoc(doc(db,'identities',currentUid)),ownMem=await getDoc(doc(db,'memberships',`mem_${currentUid}_org_saovn_01`));if(own.exists())members=[memberFrom({...own.data(),id:currentUid},ownMem.exists()?{...ownMem.data(),id:ownMem.id}:{},currentUid)];}render();}catch(error){console.error('Lỗi tải thành viên:',error);render();if(resultCount)resultCount.textContent='Không thể tải toàn bộ danh sách với quyền hiện tại';}}
function render(){const search=$('searchInput'),status=$('statusFilter'),role=$('roleFilter');if(!search||!status||!role)return;const q=search.value.trim().toLowerCase(),sf=status.value,rf=role.value,filtered=members.filter(m=>(!q?true:`${m.name} ${m.email} ${positionLabel(m.position)}`.toLowerCase().includes(q))&&(sf==='ALL'||m.status===sf)&&(rf==='ALL'||m.role===rf));if($('totalMembers'))$('totalMembers').textContent=members.length;if($('activeMembers'))$('activeMembers').textContent=members.filter(m=>m.status==='ACTIVE').length;if($('adminMembers'))$('adminMembers').textContent=members.filter(m=>m.role==='ADMIN'||m.role==='MANAGER').length;if($('inactiveMembers'))$('inactiveMembers').textContent=members.filter(m=>m.status!=='ACTIVE').length;if($('resultCount'))$('resultCount').textContent=`${filtered.length} thành viên`;if($('emptyState'))$('emptyState').hidden=filtered.length>0;const list=$('memberList');if(!list)return;list.innerHTML=filtered.map(m=>`<div class="member-row ${m.status!=='ACTIVE'?'is-not-active':''}" data-member-id="${safe(m.id)}" tabindex="${m.status==='ACTIVE'?'0':'-1'}" role="${m.status==='ACTIVE'?'button':'row'}" aria-disabled="${m.status!=='ACTIVE'}"><div class="member-info"><div class="member-avatar">${safe(initials(m.name))}</div><div><strong>${safe(m.name)}</strong><small>${safe(m.position==='OTHER'?'Khác':positionLabel(m.position))} · ${safe(m.email)}</small></div></div><span class="role ${m.role}">${safe(roleLabel(m.role))}</span><span class="status ${m.status}">${safe(statusLabel(m.status))}</span><span class="joined">${formatDate(m.joinedAt)}</span></div>`).join('');document.querySelectorAll('.member-row').forEach(row=>{const open=()=>{const member=members.find(m=>m.id===row.dataset.memberId);if(!member||member.status!=='ACTIVE')return;openMemberDetail(member);};if(row.getAttribute('aria-disabled')!=='true'){row.addEventListener('click',open);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});}});}
function openMemberDetail(member){if(!member)return;currentMember=member;const fields={detailAvatar:initials(member.name),detailName:member.name,detailEmail:member.email||'Không có email',detailPosition:positionLabel(member.position),detailRole:roleLabel(member.role),detailStatus:statusLabel(member.status),detailJoined:formatDate(member.joinedAt),detailId:member.id};Object.entries(fields).forEach(([id,value])=>{const el=$(id);if(el)el.textContent=value;});const roleSelect=$('roleSelect');if(roleSelect)roleSelect.value=member.role;const saveStatus=$('roleSaveStatus');if(saveStatus){saveStatus.textContent='';saveStatus.className='role-save-status';}const permissionGrid=$('permissionGrid');if(permissionGrid)renderPermissionGrid(permissionGrid,member.role);const overlay=$('memberDetailOverlay');if(!overlay)return;overlay.hidden=false;requestAnimationFrame(()=>overlay.classList.add('open'));}
function closeMemberDetail(){const overlay=$('memberDetailOverlay');if(!overlay)return;overlay.classList.remove('open');setTimeout(()=>overlay.hidden=true,120);currentMember=null;}
function openInvite(){const overlay=$('inviteOverlay');if(!overlay)return;const form=$('inviteForm');if(form)form.reset();const status=$('inviteStatus');if(status){status.textContent='';status.className='role-save-status';}const password=$('generatedPassword');if(password)password.textContent='—';const credentials=$('credentialsResult');if(credentials)credentials.hidden=true;const button=$('sendInviteBtn');if(button){button.textContent='Tạo tài khoản';button.disabled=false;}overlay.hidden=false;requestAnimationFrame(()=>overlay.classList.add('open'));setTimeout(()=>$('inviteName')?.focus(),60);}
function closeInvite(){const overlay=$('inviteOverlay');if(!overlay)return;overlay.classList.remove('open');setTimeout(()=>overlay.hidden=true,120);}
function formatDate(value){if(!value)return'—';try{const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('vi-VN');}catch{return'—';}}
function generatePassword(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=new Uint8Array(14);crypto.getRandomValues(bytes);return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('');}
async function getProvisioningAuth(){if(provisioningAuth)return provisioningAuth;const app=initializeApp(firebaseConfig,`saovn-provision-${Date.now()}`);provisioningAuth=getAuth(app);return provisioningAuth;}
async function provisionMemberAccount(){const name=String($('inviteName')?.value||'').trim(),email=String($('inviteEmail')?.value||'').trim().toLowerCase(),position=normalizePosition($('invitePosition')?.value||'STAFF'),role=String($('inviteRole')?.value||'MEMBER').toUpperCase(),status=$('inviteStatus'),button=$('sendInviteBtn');if(!name||!email)return;if(status){status.textContent='Đang tạo tài khoản chờ kích hoạt...';status.className='role-save-status pending';}if(button){button.disabled=true;button.textContent='Đang tạo...';}try{const identityQuery=await getDocs(collection(db,'identities'));if(identityQuery.docs.some(s=>String(s.data()?.email||'').toLowerCase()===email))throw new Error('Email này đã tồn tại trong SAOVN-OS.');const provisioningAuthInstance=await getProvisioningAuth(),password=generatePassword(),credential=await createUserWithEmailAndPassword(provisioningAuthInstance,email,password),uid=credential.user.uid;await setDoc(doc(db,'identities',uid),{uid,email,displayName:name,position,status:'PENDING',mustChangePassword:true,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});await setDoc(doc(db,'memberships',`mem_${uid}_org_saovn_01`),{uid,userId:uid,identityId:uid,organizationId:'org_saovn_01',status:'PENDING',position,roles:{system:[],organization:[roleValue(role)]},joinedAt:null,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid});try{await signOutProvisioning(provisioningAuthInstance);}catch(_){ }if($('generatedEmail'))$('generatedEmail').textContent=email;if($('generatedPassword'))$('generatedPassword').textContent=password;if($('credentialsResult'))$('credentialsResult').hidden=false;if(status){status.textContent='Đã tạo tài khoản. Thành viên phải đăng nhập bằng mật khẩu tạm để kích hoạt và đổi mật khẩu.';status.className='role-save-status success';}if(button)button.textContent='Tạo tài khoản khác';await loadMembers();}catch(error){console.error('Lỗi tạo tài khoản thành viên:',error);let message=error?.message||'Không thể tạo tài khoản.';if(error?.code==='auth/email-already-in-use')message='Email này đã có tài khoản Firebase Auth.';if(error?.code==='auth/invalid-email')message='Email không hợp lệ.';if(status){status.textContent=message;status.className='role-save-status error';}}finally{if(button)button.disabled=false;}}
[['searchInput','input'],['statusFilter','change'],['roleFilter','change']].forEach(([id,event])=>$(id)?.addEventListener(event,render));$('refreshBtn')?.addEventListener('click',loadMembers);$('logoutBtn')?.addEventListener('click',()=>signOut(auth));$('detailClose')?.addEventListener('click',closeMemberDetail);$('memberDetailOverlay')?.addEventListener('click',e=>{if(e.target.id==='memberDetailOverlay')closeMemberDetail();});$('inviteMemberBtn')?.addEventListener('click',openInvite);$('inviteClose')?.addEventListener('click',closeInvite);$('inviteOverlay')?.addEventListener('click',e=>{if(e.target.id==='inviteOverlay')closeInvite();});$('inviteForm')?.addEventListener('submit',e=>{e.preventDefault();provisionMemberAccount();});
$('copyCredentials')?.addEventListener('click',async()=>{const email=$('generatedEmail')?.textContent,password=$('generatedPassword')?.textContent;if(!email||email==='—'||!password||password==='—')return;const text=`SAOVN-OS\nEmail: ${email}\nMật khẩu tạm: ${password}`;try{await navigator.clipboard.writeText(text);const b=$('copyCredentials');b.textContent='Đã sao chép';setTimeout(()=>b.textContent='Sao chép thông tin',1500);}catch{const s=$('inviteStatus');if(s){s.textContent='Không thể sao chép tự động. Hãy copy thông tin bằng tay.';s.className='role-save-status error';}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMemberDetail();closeInvite();}});$('roleSelect')?.addEventListener('change',e=>{renderPermissionGrid($('permissionGrid'),e.target.value);const s=$('roleSaveStatus');if(s){s.textContent='Thay đổi chưa lưu';s.className='role-save-status pending';}});$('saveRoleBtn')?.addEventListener('click',async()=>{if(!currentMember)return;const role=$('roleSelect')?.value,button=$('saveRoleBtn');if(!button)return;button.disabled=true;button.textContent='Đang lưu...';const s=$('roleSaveStatus');if(s)s.textContent='';try{if(!currentMember.membershipId)throw new Error('Thành viên này chưa có Membership trong workspace.');await saveMemberRole(currentMember.membershipId,role);currentMember.role=role;const target=members.find(m=>m.id===currentMember.id);if(target)target.role=role;if($('detailRole'))$('detailRole').textContent=roleLabel(role);if(s){s.textContent='Đã lưu vai trò thành công.';s.className='role-save-status success';}render();}catch(error){console.error('Lỗi lưu vai trò:',error);if(s){s.textContent=error?.message||'Không thể lưu vai trò.';s.className='role-save-status error';}}finally{button.disabled=false;button.textContent='Lưu vai trò';}});onAuthStateChanged(auth,async user=>{if(!user){location.href='index.html';return;}currentUid=user.uid;if($('userName'))$('userName').textContent=user.displayName||user.email?.split('@')[0]||'User';if($('userAvatar'))$('userAvatar').textContent=initials(user.displayName||user.email?.split('@')[0]);await loadMembers();});