import { collection, addDoc, getDocs, updateDoc, doc, serverTimestamp, getDoc } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js";
import { auth, db } from "./firebase-config.js";
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeTaskId=null;
const identityCache=new Map();
const POSITION_LABELS={INTERN:'Thực tập sinh',COLLABORATOR:'Cộng tác viên',STAFF:'Nhân viên',SPECIALIST:'Chuyên viên',SENIOR_SPECIALIST:'Chuyên viên cao cấp',TEAM_LEAD:'Trưởng nhóm',MANAGER:'Quản lý',DEPARTMENT_HEAD:'Trưởng phòng',DIRECTOR:'Giám đốc',FOUNDER_CHAIRMAN_CEO:'Founder · Chairman · CEO',OTHER:'Khác'};
const normalizePosition=p=>String(p||'STAFF').toUpperCase();
const positionLabel=p=>POSITION_LABELS[normalizePosition(p)]||String(p||'Nhân viên');
const identityDisplay=(identity={},fallback='Thành viên')=>{const name=identity.fullName||identity.displayName||identity.name||identity.email||fallback;const position=identity.position||identity.jobTitle||'STAFF';return{name,position:positionLabel(position)}};
const membershipRef=uid=>doc(db,'memberships',`mem_${uid}_org_saovn_01`);
async function getIdentity(uid){
  if(!uid)return null;
  if(identityCache.has(uid))return identityCache.get(uid);
  try{const snap=await getDoc(doc(db,'identities',uid));if(snap.exists()){const value=snap.data();identityCache.set(uid,value);return value;}}
  catch(e){if(e?.code!=='permission-denied')console.warn('Không tải được identity:',uid,e?.code||e);}
  try{const snap=await getDoc(membershipRef(uid));if(snap.exists()){const value=snap.data();identityCache.set(uid,value);return value;}}
  catch(e){if(e?.code!=='permission-denied')console.warn('Không tải được membership hồ sơ:',uid,e?.code||e);}
  identityCache.set(uid,null);return null;
}
async function resolveAuthor(authorId,storedName){const identity=await getIdentity(authorId);return identity?identityDisplay(identity,storedName||'Thành viên'):{name:storedName||'Thành viên',position:'Nhân viên'}}
document.addEventListener('click',e=>{const target=e.target.closest('[data-detail]');if(!target||e.target.closest('[data-edit]'))return;activeTaskId=target.dataset.detail;setTimeout(()=>enhanceDetail(activeTaskId),80)});
const taskSubcollection=(taskId,name)=>collection(db,'workTasks',taskId,name);
async function enhanceDetail(taskId){const body=document.getElementById('detailBody');if(!body||!taskId||body.querySelector('.collab-section'))return;const wrap=document.createElement('div');wrap.className='collab-section';wrap.innerHTML=`<div class="collab-grid"><section class="collab-panel"><div class="collab-head"><div><span class="eyebrow">TASK / CHECKLIST</span><strong>Checklist</strong></div><span id="checkProgress">0 / 0</span></div><div class="check-add"><input id="checkInput" maxlength="160" placeholder="Thêm một việc cần làm..."><button id="addCheck">＋</button></div><div id="checkList"><span class="loading">Đang tải...</span></div></section><section class="collab-panel"><div class="collab-head"><div><span class="eyebrow">TASK / COMMENTS</span><strong>Trao đổi</strong></div><span id="commentCount">0</span></div><div id="commentList"><span class="loading">Đang tải...</span></div><div class="comment-add"><textarea id="commentInput" rows="2" maxlength="500" placeholder="Viết trao đổi về công việc..."></textarea><button id="addComment">Gửi</button></div></section></div>`;body.appendChild(wrap);injectStyles();document.getElementById('addCheck').onclick=addChecklist;document.getElementById('checkInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addChecklist()}};document.getElementById('addComment').onclick=addComment;window.dispatchEvent(new CustomEvent('work-detail-opened',{detail:{taskId}}));await Promise.all([loadChecklist(taskId),loadComments(taskId)])}
async function loadChecklist(taskId){const box=document.getElementById('checkList'),progress=document.getElementById('checkProgress');try{const s=await getDocs(taskSubcollection(taskId,'checklist'));const items=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestamp(a.createdAt)-timestamp(b.createdAt));progress.textContent=`${items.filter(x=>x.done).length} / ${items.length}`;if(!items.length){box.innerHTML='<span class="loading">Chưa có mục nào. Thêm checklist đầu tiên.</span>';return}box.innerHTML=items.map(x=>`<label class="check-item"><input type="checkbox" data-check="${x.id}" ${x.done?'checked':''}><span class="check-mark"></span><span class="check-text ${x.done?'completed':''}">${esc(x.text)}</span></label>`).join('');box.querySelectorAll('[data-check]').forEach(input=>input.onchange=async()=>{try{await updateDoc(doc(db,'workTasks',taskId,'checklist',input.dataset.check),{done:input.checked,updatedAt:serverTimestamp(),updatedBy:auth.currentUser?.uid||null});await loadChecklist(taskId)}catch(e){console.warn('Không thể cập nhật checklist:',e?.code||e);input.checked=!input.checked;alert('Không thể cập nhật checklist. Bạn không có quyền với công việc này.')}})}catch(e){console.warn('Không tải được checklist:',e?.code||e);box.innerHTML='<span class="loading">Checklist chưa có hoặc tài khoản chưa được cấp quyền cộng tác.</span>'}}
async function addChecklist(){const input=document.getElementById('checkInput');if(!input?.value.trim()||!activeTaskId)return;const text=input.value.trim();input.disabled=true;try{await addDoc(taskSubcollection(activeTaskId,'checklist'),{text,done:false,createdBy:auth.currentUser?.uid||null,createdAt:serverTimestamp()});input.value='';await loadChecklist(activeTaskId)}catch(e){console.warn('Không thể thêm checklist:',e?.code||e);alert('Không thể thêm checklist. Tài khoản chưa có quyền cộng tác với công việc này.')}finally{input.disabled=false;input.focus()}}
async function loadComments(taskId){const box=document.getElementById('commentList'),count=document.getElementById('commentCount');try{const s=await getDocs(taskSubcollection(taskId,'comments'));count.textContent=s.size;const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestamp(a.createdAt)-timestamp(b.createdAt));if(!rows.length){box.innerHTML='<span class="loading">Chưa có trao đổi nào.</span>';return}const comments=await Promise.all(rows.map(async x=>{const author=await resolveAuthor(x.authorId,x.authorName),time=x.createdAt?.toDate?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(x.createdAt.toDate()):'Vừa xong';return{...x,author,time}}));box.innerHTML=comments.map(x=>`<article class="comment"><div class="comment-avatar">${esc(x.author.name.slice(0,1).toUpperCase())}</div><div><strong data-member-profile="${esc(x.authorId||'')}">${esc(x.author.name)}</strong><span class="comment-position">${esc(x.author.position)}</span><small>${timeLabel(x.time)}</small><p>${esc(x.text)}</p></div></article>`).join('')}catch(e){console.warn('Không tải được trao đổi:',e?.code||e);box.innerHTML='<span class="loading">Chưa có trao đổi hoặc tài khoản chưa được cấp quyền cộng tác.</span>'}}
function timeLabel(value){return String(value||'Vừa xong')}
async function addComment(){const input=document.getElementById('commentInput');if(!input?.value.trim()||!activeTaskId)return;const text=input.value.trim(),u=auth.currentUser;input.disabled=true;try{const identity=await getIdentity(u?.uid);const author=identityDisplay(identity,u?.displayName||'Thành viên');await addDoc(taskSubcollection(activeTaskId,'comments'),{text,authorId:u?.uid||null,authorName:author.name,authorPosition:author.position,createdAt:serverTimestamp()});input.value='';await loadComments(activeTaskId)}catch(e){console.warn('Không thể gửi trao đổi:',e?.code||e);alert('Không thể gửi trao đổi. Tài khoản chưa có quyền cộng tác với công việc này.')}finally{input.disabled=false;input.focus()}}
function timestamp(value){if(!value)return 0;if(typeof value.toMillis==='function')return value.toMillis();if(typeof value.toDate==='function')return value.toDate().getTime();const n=new Date(value).getTime();return Number.isNaN(n)?0:n}
function injectStyles(){if(document.getElementById('collabStyles'))return;const s=document.createElement('style');s.id='collabStyles';s.textContent=`.collab-section{margin-top:18px}.collab-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.collab-panel{padding:16px;border:1px solid var(--line);border-radius:13px;background:#ffffff04}.collab-head{display:flex;align-items:end;justify-content:space-between;padding-bottom:12px;border-bottom:1px solid #fff1}.collab-head strong{font-size:11px}.collab-head>span{font-size:8px;color:#718098}.check-add{display:flex;gap:7px;margin:12px 0}.check-add input,.comment-add textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:#07101f;color:#eef4ff;padding:9px;font:9px inherit;outline:0}.check-add button,.comment-add button{border:1px solid #4b99ff66;border-radius:8px;background:#1673ef;color:white;min-width:38px;font-weight:800}.check-item{display:flex;align-items:center;gap:9px;padding:10px 2px;border-bottom:1px solid #fff1;cursor:pointer}.check-item input{display:none}.check-mark{width:16px;height:16px;border:1px solid #53657d;border-radius:5px;background:#07101f;flex:0 0 16px}.check-item input:checked+.check-mark{border-color:var(--green);background:#00e676;box-shadow:0 0 12px #00e67633}.check-item input:checked+.check-mark:after{content:'✓';display:block;color:#03100a;font-size:11px;text-align:center;font-weight:900}.check-text{font-size:9px;color:#b5c1d2}.check-text.completed{text-decoration:line-through;color:#647389}.comment{display:flex;gap:9px;padding:11px 0;border-bottom:1px solid #fff1}.comment-avatar{width:27px;height:27px;flex:0 0 27px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(145deg,#3156b9,#8b5cf6);font-size:8px}.comment strong{font-size:9px}.comment-position{display:block;margin-top:2px;color:#8ea1bb;font-size:7px}.comment small{margin-left:7px;color:#68778e;font-size:7px}.comment p{margin-top:5px;color:#a4b0c1;font-size:9px;line-height:1.5;white-space:pre-wrap}.comment-add{display:flex;gap:7px;margin-top:12px}.comment-add button{padding:0 13px}.loading{font-size:9px}.detail-card{max-width:1050px}.comment [data-member-profile]{color:#dce9ff;text-decoration:none;border-bottom:1px solid rgba(69,151,255,.28);cursor:pointer;font-weight:800}.comment [data-member-profile]:hover{color:#61adff;border-bottom-color:#61adff}@media(max-width:800px){.collab-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}