import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js";
import { collection, addDoc, getDocs, updateDoc, doc, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js";
import { auth, db } from "./firebase-config.js";

const $=id=>document.getElementById(id); const E={name:$('userName'),top:$('topUserName'),logout:$('logoutButton'),sync:$('syncState'),total:$('totalCount'),progress:$('progressCount'),done:$('doneCount'),overdue:$('overdueCount'),result:$('resultCount'),list:$('taskList'),kanban:$('kanbanBoard'),search:$('searchInput'),sf:$('statusFilter'),pf:$('priorityFilter'),modal:$('taskModal'),form:$('taskForm'),id:$('taskId'),title:$('taskTitle'),desc:$('taskDescription'),assignee:$('taskAssignee'),due:$('taskDueDate'),status:$('taskStatus'),priority:$('taskPriority'),save:$('saveTaskBtn'),boardTitle:$('boardTitle')};
let user=null,tasks=[],view='list',dragId=null; const SL={BACKLOG:'Backlog',TODO:'Todo',IN_PROGRESS:'Đang thực hiện',REVIEW:'Review',DONE:'Hoàn thành'},PL={LOW:'Thấp',MEDIUM:'Trung bình',HIGH:'Cao',URGENT:'Khẩn cấp'}; const STATES=Object.keys(SL);

onAuthStateChanged(auth,async u=>{if(!u){location.href='index.html';return}user=u;try{const s=await getDocs(collection(db,'identities'));const d=s.docs.find(x=>x.id===u.uid)?.data();const n=d?.fullName||u.displayName||u.email?.split('@')[0]||'Admin';E.name.textContent=n;E.top.textContent=n;await load();E.sync.innerHTML='<i></i> Firebase · Đã đồng bộ'}catch(e){console.error(e);E.sync.innerHTML='<i style="background:#ff3b3b;box-shadow:0 0 8px #ff3b3b"></i> Firebase · Lỗi kết nối';render()}});
async function load(){const s=await getDocs(query(collection(db,'workTasks'),orderBy('createdAt','desc')));tasks=s.docs.map(d=>({id:d.id,...d.data()}));render()}
function visible(){const q=E.search.value.trim().toLowerCase();return tasks.filter(t=>(!q||`${t.title||''} ${t.description||''} ${t.assignee||''}`.toLowerCase().includes(q))&&(E.sf.value==='ALL'||t.status===E.sf.value)&&(E.pf.value==='ALL'||t.priority===E.pf.value))}
function render(){const today=new Date().toISOString().slice(0,10);E.total.textContent=tasks.length;E.progress.textContent=tasks.filter(t=>t.status==='IN_PROGRESS').length;E.done.textContent=tasks.filter(t=>t.status==='DONE').length;E.overdue.textContent=tasks.filter(t=>t.dueDate&&t.dueDate<today&&t.status!=='DONE').length;const v=visible();E.result.textContent=`${v.length} công việc`;if(view==='list'){E.list.style.display='block';E.kanban.classList.remove('active');E.boardTitle.textContent='Danh sách công việc';renderList(v)}else{E.list.style.display='none';E.kanban.classList.add('active');E.boardTitle.textContent='Kanban Work';renderKanban(v)}}
function renderList(v){if(!v.length){E.list.innerHTML=`<div class="empty"><div>▱</div><strong>${tasks.length?'Không tìm thấy công việc':'Chưa có công việc'}</strong><span>${tasks.length?'Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm.':'Tạo công việc đầu tiên để bắt đầu vận hành Work.'}</span><button class="outline-btn" id="emptyCreateBtn">＋ Tạo công việc</button></div>`;$('emptyCreateBtn').onclick=openCreate;return}E.list.innerHTML=v.map(row).join('');E.list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(tasks.find(t=>t.id===b.dataset.edit)))}
function row(t){const today=new Date().toISOString().slice(0,10),over=t.dueDate&&t.dueDate<today&&t.status!=='DONE',dot=t.status==='DONE'?'#55aaff':t.status==='IN_PROGRESS'?'#00e676':t.status==='REVIEW'?'#ff9f1c':t.priority==='URGENT'?'#ff3b3b':'#2587ff';return `<div class="task-row"><div class="task-main"><i class="task-dot" style="color:${dot};background:${dot}"></i><div><strong>${esc(t.title||'Không tên')}</strong><small>${esc(t.description||'Chưa có mô tả')}</small></div></div><span class="status ${t.status||'TODO'}">${SL[t.status]||'Todo'}</span><span class="priority ${t.priority||'MEDIUM'}">${PL[t.priority]||'Trung bình'}</span><span class="assignee">${esc(t.assignee||'Chưa giao')}</span><span class="due ${over?'overdue':''}">${t.dueDate?date(t.dueDate):'Không deadline'}</span><button class="row-menu" data-edit="${t.id}" title="Sửa">⋮</button></div>`}
function renderKanban(v){E.kanban.innerHTML=STATES.map(status=>{const items=v.filter(t=>(t.status||'TODO')===status);return `<div class="kanban-col" data-status="${status}"><div class="kanban-col-head"><strong>${SL[status]}</strong><span>${items.length}</span></div><div class="kanban-items">${items.map(kanbanCard).join('')}</div></div>`}).join('');wireKanban()}
function kanbanCard(t){const today=new Date().toISOString().slice(0,10),over=t.dueDate&&t.dueDate<today&&t.status!=='DONE';return `<article class="kanban-card" draggable="true" data-id="${t.id}"><strong>${esc(t.title||'Không tên')}</strong><p>${esc(t.description||'Chưa có mô tả')}</p><div class="kanban-meta"><span class="kanban-assignee">${esc(t.assignee||'Chưa giao')}</span><span class="kanban-priority ${t.priority||'MEDIUM'}">${PL[t.priority]||'Trung bình'}</span></div><div class="kanban-meta"><span class="kanban-due ${over?'overdue':''}">${t.dueDate?date(t.dueDate):'Không deadline'}</span><button class="row-menu" data-edit="${t.id}" title="Sửa">⋮</button></div></article>`}
function wireKanban(){E.kanban.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEdit(tasks.find(t=>t.id===b.dataset.edit))});E.kanban.querySelectorAll('.kanban-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragId=card.dataset.id;card.classList.add('dragging')});card.addEventListener('dragend',()=>{dragId=null;card.classList.remove('dragging');E.kanban.querySelectorAll('.kanban-col').forEach(c=>c.classList.remove('drag-over'))})});E.kanban.querySelectorAll('.kanban-col').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');if(!dragId)return;const t=tasks.find(x=>x.id===dragId),status=col.dataset.status;if(!t||t.status===status)return;await moveTask(t,status)})})}
async function moveTask(t,status){try{await updateDoc(doc(db,'workTasks',t.id),{status,updatedBy:user.uid,updatedAt:serverTimestamp()});t.status=status;render()}catch(e){console.error(e);alert('Không thể cập nhật trạng thái. Hãy kiểm tra Firebase/Firestore Rules.')}}
function date(v){return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T00:00:00'))}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openCreate(){E.form.reset();E.id.value='';E.status.value='TODO';E.priority.value='MEDIUM';$('modalTitle').textContent='Tạo công việc';E.modal.classList.add('open');E.title.focus()}function openEdit(t){if(!t)return;$('modalTitle').textContent='Chỉnh sửa công việc';E.id.value=t.id;E.title.value=t.title||'';E.desc.value=t.description||'';E.assignee.value=t.assignee||'';E.due.value=t.dueDate||'';E.status.value=t.status||'TODO';E.priority.value=t.priority||'MEDIUM';E.modal.classList.add('open');E.title.focus()}function close(){E.modal.classList.remove('open')}
$('newTaskBtn').onclick=openCreate;$('closeModal').onclick=close;$('cancelModal').onclick=close;E.modal.onclick=e=>{if(e.target===E.modal)close()};E.search.oninput=render;E.sf.onchange=render;E.pf.onchange=render;document.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.view-btn').forEach(x=>x.classList.toggle('active',x===b));render()});
E.form.onsubmit=async e=>{e.preventDefault();E.save.disabled=true;E.save.textContent='Đang lưu...';const data={title:E.title.value.trim(),description:E.desc.value.trim(),assignee:E.assignee.value.trim(),dueDate:E.due.value||null,status:E.status.value,priority:E.priority.value,updatedBy:user.uid,updatedAt:serverTimestamp()};try{if(E.id.value)await updateDoc(doc(db,'workTasks',E.id.value),data);else await addDoc(collection(db,'workTasks'),{...data,createdBy:user.uid,createdAt:serverTimestamp()});close();await load()}catch(e){console.error(e);alert('Không thể lưu công việc. Hãy kiểm tra Firebase/Firestore Rules.')}finally{E.save.disabled=false;E.save.textContent='Lưu công việc'}};E.logout.onclick=()=>signOut(auth).catch(console.error);
